deployment:
  tasks:
    - export DEPLOYPATH=/home/teketeq9v8o0/staging.teketesafespace.co.za
    - export PHP=/opt/cpanel/ea-php82/root/usr/bin/php
    - if [ ! -x "$PHP" ]; then export PHP=$(command -v php); fi
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && $PHP artisan migrate --force
    - cd $DEPLOYPATH && $PHP artisan optimize:clear
