<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Provincial Report - {{ $provinceName }}</title>
    <style>
        body { 
            font-family: DejaVu Sans, sans-serif; 
            font-size: 12px; 
            margin: 25px 30px 25px 30px; 
            color: #222;
        }

        header {
            display: flex;
            align-items: center; 
            border-bottom: 2px solid #000;
            padding-bottom: 8px;
            margin-bottom: 15px;
        }

       
        header img {
            width: 150px;
            height: auto;
           
            margin-right: 10px; 
        }

        .header-text {
            display: flex;
            flex-direction: column;
        }

        header h1 {
            margin: 0;
            font-size: 22px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        header p {
            margin: 2px 0 0 0;
            font-size: 12px;
            color: #555;
        }

        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 10px; 
        }

        th, td { 
            border: 1px solid #444; 
            padding: 6px 8px; 
            text-align: left; 
            vertical-align: top;
        }

        th { 
            background-color: #cce57b; 
            font-weight: bold;
            text-transform: uppercase;
            font-size: 12px;
        }

        td {
            font-size: 11px;
            line-height: 1.4;
        }

        .footer {
            text-align: center;
            font-size: 10px;
            color: #777;
            margin-top: 25px;
        }
    </style>
</head>
<body>
    <header>
        <img src="{{ public_path('images/favicon.png') }}" alt="Logo">
        <div class="header-text">
            <h1>Provincial Report</h1>
            <p><strong>Province:</strong> {{ $provinceName }}</p>
            <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('d M Y, H:i') }}</p>
        </div>
    </header>

    @if($reports->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>Case Number</th>
                    <th>Reporter Email</th>
                    <th>Abuse Type</th>
                    <th>Status</th>
                    <th>Description</th>
                    <th>Date Reported</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reports as $report)
                <tr>
                    <td>{{ $report->case_number }}</td>
                    <td>{{ $report->reporter_email ?? 'N/A' }}</td>
                    <td>{{ $report->abuseType->type_name ?? 'Unknown' }}</td>
                    <td>{{ ucfirst($report->status) }}</td>
                    <td style="white-space: normal; word-wrap: break-word;">
                        {{ Str::limit(strip_tags($report->description ?? 'No description'), 150) }}
                    </td>
                    <td>{{ $report->created_at->format('d-m-Y') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>No reports found for this province.</p>
    @endif

    <div class="footer">
        <p>Confidential Report — Generated by Safe Space Platform</p>
    </div>
</body>
</html>
